---

- name: create basic AWS security groups
  ec2_group:
    profile: phaban-inc
    region: us-east-1
    state: present
    name: "{{ item.name }}"
    description: "{{ item.description }}"
    vpc_id: "{{ aws_vpc.vpc_id }}"
    purge_rules: False
    purge_rules_egress: False
  register: aws_security_groups
  with_items: "{{ aws_security_groups_vars }}"

- name: create complex AWS security groups
  ec2_group:
    profile: phaban-inc
    region: us-east-1
    state: present
    name: "{{ item.name }}"
    description: "{{ item.description }}"
    vpc_id: "{{ aws_vpc.vpc_id }}"
    purge_rules: True
    purge_rules_egress: False
    rules: "{{ item.rules }}"
  register: aws_security_groups
  with_items: "{{ aws_security_groups_vars }}"

#- debug: var=aws_security_groups
