---

- name: get ec2 facts
  ec2_facts:
  
- name: Retrieve all tags on an instance
  ec2_tag:
    region: us-east-1
    resource: "{{ ansible_ec2_instance_id }}"
    state: list
  register: ec2_tags
  
#- debug: var=ec2_tags

